# Generated by Django 6.0.3 on 2026-05-02 09:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_user_report'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inappnotification',
            name='hidden',
            field=models.BooleanField(db_index=True, default=False, help_text='Ukryte: użytkownik miał otwarty ten kanał / tę rozmowę — bez listy i bez pushu WS.'),
        ),
        migrations.AddIndex(
            model_name='inappnotification',
            index=models.Index(fields=['user', 'hidden'], name='chat_inappn_user_id_319bba_idx'),
        ),
    ]
