# Generated by Django 6.0.3 on 2026-04-25 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pytanie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tresc', models.CharField(max_length=200)),
                ('data_publikacji', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
